apiVersion: batch/v1
kind: Job
metadata:
  name: shopping-cart-load-driver
spec:
  template:
    spec:
      volumes:
        - name: shopping-cart-load-driver-pvc
          persistentVolumeClaim:
            claimName: shopping-cart-load-driver-pvc
      containers:
        - name: shopping-cart-load-driver
          image: northamerica-northeast2-docker.pkg.dev/scylla-cassandra-comparison/load-test/shopping-cart-load-test-driver:0.2.0-SNAPSHOT
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/mnt/"
              name: shopping-cart-load-driver-pvc
          env:
            - name: RANDOM_PAYLOAD_SIZE
              value: "50"  # value in bytes
            - name: TARGET_HOST
              value: "shopping-cart-service"  # service hostname exposed by shopping-cart-service
            - name: TARGET_PORT
              value: "8101"
            - name: TEST_DURATION
              value: "30.seconds"
            - name: USERS_PER_SECOND
              value: "1"
            - name: RESULT_BASE_DIR
              value: "/mnt/" # should pick/set a more appropriate mount path
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      restartPolicy: Never
  backoffLimit: 2
  completions: 1
