apiVersion: batch/v1
kind: Job
metadata:
  name: shopping-cart-load-driver
spec:
  template:
    spec:
      volumes:
        - name: shopping-cart-load-driver-storage
          persistentVolumeClaim:
            claimName: shopping-cart-load-driver-pvc
      containers:
        - name: shopping-cart-load-driver
          image: shopping-cart-load-test/shopping-cart-load-test-driver:0.1.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: "/mnt/simulation-data"
              name: shopping-cart-load-driver-storage
          env:
            - name: RANDOM_PAYLOAD_SIZE
              value: "50"  # value in bytes
            - name: TARGET_HOST
              value: "shopping-cart-service"  # service hostname exposed by shopping-cart-service
            - name: TARGET_PORT
              value: "8101"
            - name: TEST_DURATION
              value: "30.seconds"
            - name: USERS_PER_SECOND
              value: "1"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      restartPolicy: Never
  backoffLimit: 4
  completions: 1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shopping-cart-load-driver-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
# This PV is a common, persistent volume to collect simulation results of load tests across nodes, runs.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shopping-cart-load-driver-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    # TODO:  must be replaced with a cloud resource in a real deployed scenario
    # TODO:  maps to a local directory as demonstration, replace accordingly
    path: "/Users/dkichler/projects/scylla-pov/akka-cqrs-cart-example/load-testing/results"
