apiVersion: v1
kind: Pod
metadata:
  name: results
spec:
  securityContext:
    runAsUser: 0
    runAsGroup: 0
  volumes:
    - name: load-test-results-storage
      persistentVolumeClaim:
        claimName: shopping-cart-load-driver-pvc
  containers:
    - name: results
      image: northamerica-northeast2-docker.pkg.dev/scylla-cassandra-comparison/load-test/ubuntu:20.04
      command: [ "/bin/sh" , "-c", "tail -f /dev/null" ]
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: load-test-results-storage
          mountPath: /mnt/simulation-data  # the shared directory
  restartPolicy: Always
