apiVersion: v1
kind: Service
metadata:
  name: cassandra-single
spec:
  selector:
    app: cassandra-single
  clusterIP: None
---
apiVersion: v1
kind: Pod
metadata:
  name: cassandra-single
  labels:
    app: cassandra-single
spec:
  hostname: cassandra-1
  subdomain: cassandra-single
  containers:
    - name: cassandra-single
      image: cassandra:latest
      imagePullPolicy: Always
      ports:
        - name: cql
          containerPort: 9042
      resources:
        requests:
          cpu: "1000m"
          memory: "4Gi"
        limits:
          cpu: "2000m"
          memory: "4Gi"
