apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: test-pod
spec:
  containers:
    - name: test-pod
      image: travelping/nettools:latest
      imagePullPolicy: Always
      resources:
        requests:
          cpu: "250m"
          memory: "250Mi"
        limits:
          memory: "500Mi"
